chore: send errors to Sentry
snapshot-labs/snapshot-sidekick pull request #102
Opened 2023-07-01 06:06 UTC by wa0x6e

Setup sentry

- Send all unhandled errors to Sentry through Express error handler
- Send all captured errors via try/catch to Sentry

2023-07-04 13:25 UTC, Todmy commented
I think you should move all Sentry initializations to a separate file. This will allow you to transfer the solution to other projects more conveniently. Another advantage of this is that third parties will be encapsulated, allowing us to modify it more easily.

2023-07-04 13:31 UTC, wa0x6e commented
Should be better ?

2023-07-04 13:32 UTC, Todmy requested changes
I think it would be nice to configure [distributed tracing](https://blog.sentry.io/distributed-tracing-101-for-full-stack-developers/). It will allow us to track different request through all our apps

2023-07-04 13:32 UTC, Todmy commented on src/index.ts
> +    ...Sentry.autoDiscoverNodePerformanceMonitoringIntegrations()
it could send a lot of requests to the sentry (so we can exceed limits for the account) - we need to observe

2023-07-04 13:38 UTC, Todmy commented
> Should be better ?

much better 😊
but let's encapsulate it more:
```
import * as Sentry from '@sentry/node';
// ...
Sentry.captureException(e);
```
to
```
import logger from 'loger';
// ...
logger.capture(e);
```
I would also recommend renaming `sentry` to `logger` to make it more general

2023-07-04 13:49 UTC, wa0x6e commented
I propose to keep the filename as "sentry", for easier searching. `logger` also does seem too generic, and may be confused with the simple logger like betterstack. We already use `msyql.ts`

2023-07-04 13:51 UTC, Todmy commented
> I propose to keep the filename as "sentry", for easier searching. `logger` also does seem too generic, and may be confused with the simple logger like betterstack. We already use `msyql.ts`

but we are going to remove Betterstack, aren't we?

2023-07-04 13:57 UTC, wa0x6e commented
> > I propose to keep the filename as "sentry", for easier searching. `logger` also does seem too generic, and may be confused with the simple logger like betterstack. We already use `msyql.ts`
> 
> but we are going to remove Betterstack, aren't we?

AFAIK, no, betterstack will still be used to track logs

2023-07-06 01:04 UTC, wa0x6e commented
@Todmy any more changes needed for this PR ?

2023-07-10 13:17 UTC, Todmy approved these changes
tACK

2023-07-10 13:29 UTC, merged